### ISSUE TITLE
Show Flipped?

### ISSUE THREAD

**Issue by impallari** [Mark2Mark/Show-Rotated#1]
This script is very good for some letters, but for others like /v I want it flipped, not rotated. Any chance you can add that functionality?

**Comment by Mark2Mark** [comment]
Thanks for the request. I’ll see what I can do. I still try to find out ways to customize reporter plugins. One option is the rotation value from the transformations palette as introduced here recently. How about triggering a flip if the user puts "-180" in there?

**Comment by impallari** [comment]
Well, yeah. That will be better that nothing.
This also gives me and idea for for combining many of your script into a bigger tool. For example integrating some of the functionality of show rotated + show siblings scrips into a single one (adding some kind of user interface to it, to be able to quickly change all the possible background options for each glyph).

**Comment by Mark2Mark** [comment]
Right, that is exactly what I am planning to do. The same for other, yet unpublished plugins.
Re Show Rotated: Now I also think about a way to choose which direction it flips. One hack (e.g. `180°`) wouldn’t be enough. You have some ideas?
The Show Siblings is currently worked on. I introduce a Custom Parameter to define (per Font) if your `a` and `g` are multiple storey (italic construction) and if so, pass them into their groups. Here I also thought about flipping certain shapes (like bringing the `V`and `A`together, etc). This will be updated pretty soon.

So in general I still kind of wait for the opportunity to have something like a UI. Georg told me, reporterPlugins can only be triggered via the context menu. I’ll see what I can get/make.

Thanks so much for the input. Always appreciated!

**Comment by weiweihuanghuang** [comment]
Why not define a list of glyphs that should be rotated and those should be flipped, and also let users edit this?

**Comment by Mark2Mark** [comment]
This is a good idea. Currently there are two statuses:
1) I can make this possible by adding a Custom Parameter to add the Flipped candidates. (I would not define any glyphs by default, since this depends strongly on each design)
2) I consider making a super tiny UI now (since I can do this finally) … Plan is to have a TextBox for User Input defining the angle of Rotation, and 2 CheckBoxes: flip H / flip V

How about that?

**Comment by weiweihuanghuang** [comment]
1. How does the custom parameter work?
2. Sounds good to me :)

**Comment by Mark2Mark** [comment]
1. For some reason I cannot find it just now, I implemented it in a version of the ShowSiblings Plugin (which is currently under development for broad extension). Anyway the basic idea is to put a CP in your Font Info, something like: "ShowRotated;FlippedV: a, b, u.ss01" etc.
   This could help to save theses settings along with each .glyphs-file.

Though I asume that having a UI, the CP won’t be too nessecary anymore?!

**Comment by Mark2Mark** [comment]
I finally added a Horizontal Flip option. Is vertical also needed?

**Comment by weiweihuanghuang** [comment]
just wanted to say awesome job on the context UI menu!!

**Comment by Mark2Mark** [comment]
Thanks. Still learning and trying to improve :)

**Comment by impallari** [comment]
> I finally added a Horizontal Flip option.
> Great!
> 
> Is vertical also needed?
> Yeah, why not?

**Comment by Mark2Mark** [comment]
Just asking because it adds complexity to the general UI. If it is seldomly needed, maybe its too much functionality?

**Comment by Mark2Mark** [comment]
@impallari Just got back to this one. I added the horizontal flipping long time ago and now also the vertical flip. Hope that helps :)
